export default {
  G_REQUEST_START: 'G_REQUEST_START',
  G_REQUEST_COMPLETED: 'G_REQUEST_COMPLETED',

  MASK_NOTIFICATION_READ: 'MASK_NOTIFICATION_READ',
  MASK_ALL_NOTIFICATION_READ: 'MASK_ALL_NOTIFICATION_READ',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
}